export default {
    state: {
        code: [
            {
                params: [],
                error: false,
                text: [''],
                line: 0,
                id: 'bf36ebf1-6fb4-4bc8-877c-acc4f90f47b6',
            },
        ],
        theme: 'system',
        speed: 500,
        open: false,
        textareaValue: '',
        isCodeCorrect: false,
        isCodeOpen: true,
        turtlePosition: { x: 448, y: 416 },
        turtleSize: { width: 20, height: 30 },
        tension: 0.6,
        direction: 90,
        grid: true,
        gridSize: 32,
        canvasSize: { width: 898, height: 834 },
        trails: [
            {
                points: [448, 416, 448, 416],
                strokeWidth: 1,
                render: false,
                color: 'rgb(256, 256, 256)',
                duration: 0,
            },
        ],
        isAnimating: false,
        step: 0,
        pendown: true,
        pencolor: 'black',
        steps: [
            {
                x: 448,
                y: 416,
                rotation: 90,
                duration: 0,
                color: [256, 256, 256],
                width: 1,
                draw: false,
            },
        ],
        currStep: {
            x: 448,
            y: 416,
            rotation: 90,
            duration: 0,
            color: [256, 256, 256],
            width: 1,
            draw: false,
        },
        prevStep: {
            x: 448,
            y: 416,
            rotation: 90,
            duration: 0,
            color: [256, 256, 256],
            width: 1,
            draw: false,
        },
    },
    version: 0,
}
